// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ14Hw6VrbE45_589uhi0l9guXnNycJnA',
    appId: '1:295065187777:web:c3379db9c0d8668eb7ab40',
    messagingSenderId: '295065187777',
    projectId: 'weather-app-46313',
    authDomain: 'weather-app-46313.firebaseapp.com',
    storageBucket: 'weather-app-46313.firebasestorage.app',
    measurementId: 'G-C09DKDS8HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpn0PbA4DeakrVVlujfdqoxeGbKZnAW4',
    appId: '1:295065187777:android:3c65e5ebb988ec28b7ab40',
    messagingSenderId: '295065187777',
    projectId: 'weather-app-46313',
    storageBucket: 'weather-app-46313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvU6cIqOxjg6T90mVaddJbRxb_cZ3ia9c',
    appId: '1:295065187777:ios:536368c65a54f414b7ab40',
    messagingSenderId: '295065187777',
    projectId: 'weather-app-46313',
    storageBucket: 'weather-app-46313.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
